import subprocess
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Optional, Tuple
from .config import settings


def _run_git(args: List[str], cwd: str, timeout: int = 30) -> Dict:
    try:
        result = subprocess.run(
            ["git"] + args,
            cwd=cwd, capture_output=True, text=True, timeout=timeout
        )
        return {
            "ok": result.returncode == 0,
            "stdout": result.stdout.strip(),
            "stderr": result.stderr.strip(),
        }
    except Exception as e:
        return {"ok": False, "stdout": "", "stderr": str(e)}


def has_remote(product_path: str) -> bool:
    result = _run_git(["remote"], product_path)
    return result["ok"] and bool(result["stdout"].strip())


def get_current_branch(product_path: str) -> str:
    result = _run_git(["rev-parse", "--abbrev-ref", "HEAD"], product_path)
    return result["stdout"] if result["ok"] else "main"


def stash_dirty(product_path: str) -> str:
    """Stash all uncommitted changes. Returns stash ref name or '' if nothing stashed."""
    result = _run_git(
        ["stash", "push", "--include-untracked", "-m", "produpos-pre-update"],
        product_path
    )
    if result["ok"] and "No local changes" not in result["stdout"] and result["stdout"]:
        return "stash@{0}"
    return ""


def pop_stash(product_path: str) -> bool:
    result = _run_git(["stash", "pop"], product_path)
    return result["ok"]


def create_branch(product_path: str, product_name: str) -> str:
    if not settings.allow_git_branch_creation:
        return ""
    timestamp = datetime.utcnow().strftime("%Y%m%d-%H%M")
    safe_name = product_name.lower().replace(" ", "-").replace("_", "-")
    branch = f"produpos/update-{timestamp}-{safe_name}"
    result = _run_git(["checkout", "-b", branch], product_path)
    if result["ok"]:
        return branch
    return ""


def checkout_branch(product_path: str, branch: str) -> bool:
    result = _run_git(["checkout", branch], product_path)
    return result["ok"]


def stage_files(product_path: str, file_paths: List[str]) -> bool:
    for fp in file_paths:
        _run_git(["add", fp], product_path)
    return True


def commit_changes(
    product_path: str,
    feature_title: str,
    product_name: str,
    version_before: str,
    version_after: str,
    files_changed: List[str],
) -> str:
    if not settings.allow_git_commits:
        return ""

    subject = f"ProdupOS: add {feature_title} for {product_name}"
    body = (
        f"Feature: {feature_title}\n"
        f"Why: Auto-implemented by ProdupOS for high customer impact.\n"
        f"Files: {', '.join(files_changed)}\n"
        f"Version: {version_before or 'none'} → {version_after}"
    )
    message = f"{subject}\n\n{body}"

    result = _run_git(["commit", "-m", message], product_path)
    if result["ok"]:
        sha_result = _run_git(["rev-parse", "--short", "HEAD"], product_path)
        return sha_result["stdout"] if sha_result["ok"] else ""
    return ""


def push_branch(product_path: str, branch: str) -> Tuple[bool, str]:
    """Push branch to origin. Returns (success, message)."""
    if not has_remote(product_path):
        return False, "no remote configured"
    result = _run_git(["push", "-u", "origin", branch], product_path, timeout=60)
    if result["ok"]:
        return True, f"pushed to origin/{branch}"
    return False, result["stderr"][:200]


def get_remote_url(product_path: str) -> Optional[str]:
    result = _run_git(["remote", "get-url", "origin"], product_path)
    if result["ok"] and result["stdout"]:
        return result["stdout"]
    return None


def create_github_pr(
    product_path: str,
    branch: str,
    base_branch: str,
    feature_title: str,
    product_name: str,
    why: str,
) -> Optional[str]:
    if not settings.allow_github_pr or not settings.github_token:
        return None

    remote_url = get_remote_url(product_path)
    if not remote_url or "github.com" not in remote_url:
        return None

    parts = remote_url.rstrip(".git").split("github.com")[-1].strip("/").split("/")
    if len(parts) < 2:
        return None
    owner_repo = f"{parts[0]}/{parts[1]}"

    try:
        import httpx
        headers = {
            "Authorization": f"Bearer {settings.github_token}",
            "Accept": "application/vnd.github+json",
        }
        payload = {
            "title": f"ProdupOS: {feature_title}",
            "head": branch,
            "base": base_branch,
            "body": (
                f"## Summary\n\n{why}\n\n"
                f"## Auto-generated by ProdupOS\n"
                f"Product: {product_name}\n"
                f"Feature: {feature_title}\n"
            ),
        }
        resp = httpx.post(
            f"https://api.github.com/repos/{owner_repo}/pulls",
            json=payload, headers=headers, timeout=30,
        )
        if resp.status_code == 201:
            return resp.json().get("html_url")
    except Exception:
        pass
    return None
